[project]
name = "minerva"
version = "0.1.0"
description = "LLM-based Single Best Answer Question Generation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.2.10",
    "langchain>=0.3.9",
    "pydantic>=2.10.2",
    "typer>=0.14.0",
    "chromadb>=0.5.21",
    "langchain-community>=0.3.9",
    "pypdf>=5.1.0",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "ipython>=8.30.0",
]
